[package]
name = "ingester"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
chrono = { version = "0.4.44", features = ["serde"] }
csv = "1.4.0"
dotenvy = "0.15.7"
reqwest = { version = "0.13.3", features = ["json", "gzip"] }
serde = { version = "1.0.228", features = ["derive"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "chrono"] }
tokio = { version = "1.52.3", features = ["full"] }
zip = "8.6.0"

market_core = { path = "../../crates/market_core" }
db = { path = "../../crates/db" }
clap = { version = "4", features = ["derive"] }
futures = "0.3.32"
